# Generated by Django 5.2.3 on 2025-06-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfiguration',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('flash_enabled', models.BooleanField(default=True, verbose_name='Enable ESP32 Flash')),
                ('delay_seconds', models.PositiveIntegerField(default=10, verbose_name='Delay Between Photos (seconds)')),
                ('default_model', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini (Recommended)'), ('gpt-4o', 'GPT-4o '), ('gpt-4.1-mini', 'GPT-4.1 Mini'), ('gpt-4.1', 'GPT-4.1')], default='gpt-4o-mini', max_length=50, verbose_name='Default AI Model')),
                ('prompt_context', models.TextField(blank=True, help_text="Describe specific concerns, e.g., 'check for fire hazards' or 'monitor for unauthorized access'.", verbose_name='Custom Prompt Context')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configurations',
            },
        ),
        migrations.AddField(
            model_name='changedetectionlog',
            name='model_used',
            field=models.CharField(blank=True, max_length=50, verbose_name='AI Model Used'),
        ),
    ]
