# Generated by Django 5.0.6 on 2025-07-02 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0002_deviceconfiguration_changedetectionlog_model_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deviceconfiguration",
            name="default_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "GPT-4o Mini (Recommended)"),
                    ("gpt-4o", "GPT-4o "),
                    ("gpt-4.1-mini", "GPT-4.1 Mini"),
                    ("gpt-4.1", "GPT-4.1"),
                ],
                default="gpt-4.1-mini",
                max_length=50,
                verbose_name="Default AI Model",
            ),
        ),
    ]
