# Generated by Django 5.0.6 on 2025-07-08 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
        ("vision", "0004_changedetectionlog_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deviceconfiguration",
            options={
                "verbose_name": "Device Configuration",
                "verbose_name_plural": "Device Configurations",
            },
        ),
        migrations.AddField(
            model_name="deviceconfiguration",
            name="api_key",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="config",
                to="authentication.userapikey",
                verbose_name="API Key",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deviceconfiguration",
            name="default_model",
            field=models.CharField(
                choices=[
                    ("gpt-4o-mini", "GPT-4o Mini (Recommended)"),
                    ("gpt-4o", "GPT-4o "),
                    ("gpt-4.1-mini", "GPT-4.1 Mini"),
                    ("gpt-4.1", "GPT-4.1"),
                ],
                default="gpt-4o-mini",
                max_length=50,
                verbose_name="Default AI Model",
            ),
        ),
        migrations.AlterField(
            model_name="deviceconfiguration",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
